### ISSUE TITLE
2.10.1 can not read files with umlauts in path

### ISSUE THREAD

**Issue by tipuraneo** [kornelski/pngquant#265] opened 2017-09-11 14:57 UTC
After updating from 2.9 (unsure) to 2.10.1 pngquant can not read files with umlauts in path:

`C:\Program Files\pngquant>"Drag PNG here to reduce palette automatically.bat" "C:\Users\user.DOM\Zwischen\Pläne\Image.png"
C:\Users\user.DOM\Zwischen\Pl├ñne\Image.png:
  error: cannot open C:\Users\user.DOM\Zwischen\Pl├ñne\Image.png for reading
There were errors quantizing 1 file out of a total of 1 file.
C:\Users\user.DOM\Zwischen\Pl├ñne\Image.png:
  error: cannot open C:\Users\user.DOM\Zwischen\Pl├ñne\Image.png for reading
There were errors quantizing 1 file out of a total of 1 file.`

Executing

`C:\Program Files\pngquant>"Drag PNG here to reduce palette automatically.bat" "C:\Users\user.DOM\Zwischen\Plaene\Image.png"`

works as expected.

**Comment by pornel** [comment] 2017-09-11 23:00
Thanks for the report. The fix [is coming](https://github.com/rust-lang-nursery/getopts/pull/55).

**Comment by tipuraneo** [comment] 2017-10-19 05:21
When will the fix/next version be released?

**Comment by pornel** [comment] 2017-10-19 08:30
So it turned out the problem was worse than I expected. I thought bug was caused by a new argument parsing library, but it wasn't. The cause is due to a fundamental fuck-up in Microsoft's standard library.

In 2.10 I've switched from GCC/mingw compiler to Microsoft Visual Studio, naively assuming it would support Windows better than a "unix" compiler. But it does not! Microsoft's C compiler *does not support* Unicode paths in standard C functions. The whole path handling in Microsoft's toolchain is a terrible mess.

So Unicode paths won't work on Windows probably until I release pngquant 3.x, which may be in a couple of months.

**Comment by jibsen** [comment] 2017-11-03 09:24
I think this might be an issue with Rust rather than Windows. The mingw-w64 builds I use work fine with paths containing non-ascii characters (and also include the wildcard expansion from the mingw runtime which is missing in the recent Rust builds).

**Comment by pornel** [comment] 2017-11-03 16:38
AFAIK pure Rust code handles Unicode filenames fine. MinGW makes Unicode filenames work by adding a compatibility layer to C stdlib that makes `char *` paths UTF-8.

The problem here is that Windows/MSVC itself doesn't support UTF-8 in C stdlib. AFAIK MSVC's C stdlib functions are just an unworkable legacy codepage horror.  It expects programs to use Windows-specific methods to handle non-ASCII paths, but pngquant doesn't have Windows-specific code.

I plan to avoid this mess by using 100% pure Rust for file I/O, and Rust's stdlib handles filenames better than C stdlib.

**Comment by jibsen** [comment] 2017-11-03 16:53
After some playing around with this I tend to agree, filenames with unicode symbols not present in the ascii codepage sometimes give problems when you try to pass them to a program from a command prompt window.

The only problem with Rust is that it does not provide wildcard expansion on Windows (as far as I know).

**Comment by pornel** [comment] 2017-11-03 16:58
Oh, that's possible. In Unix world expansion is done by the shell, not the program. I didn't know mingw emulated that, too.

**Comment by jibsen** [comment] 2017-11-03 17:17
Mingw has some code that performs the expansion before main is called, yes. MSVC has something similar, you just have to link with `setargv.obj`, which comes with the compiler.

**Comment by tipuraneo** [comment] 2017-11-15 07:38
Hi guys,

I downloaded 

`C:\Program Files\pngquant>pngquant.exe
pngquant, 2.11.2 (November 2017), by Kornel Lesinski, Greg Roelofs.
   Color profiles are supported via Little CMS. Using libpng 1.6.34.`

on my Windows 8.1 x64
but Encoding Problem remains.

`C:\Program Files\pngquant>"Drag PNG here to reduce palette automatically.bat" "C:\Pläne\+00 EG WLAN Ist.png"
C:\Pl├ñne\+00 EG WLAN Ist.png:
  error: cannot open C:\Pl├ñne\+00 EG WLAN Ist.png for reading
There were errors quantizing 1 file out of a total of 1 file.`

Where can I find a compiled Windows binary I can use temporarily till the bug is fixed?

**Comment by jibsen** [comment] 2017-11-15 08:33
You could try the binaries from [pngquant-winbuild](https://github.com/jibsen/pngquant-winbuild/releases), but depending on if the character is in the codepage of the terminal or not, it may still not work.

**Comment by tipuraneo** [comment] 2017-11-15 09:13
In my case it does work. Thx.

**Comment by Js41637** [comment] 2017-11-17 10:55
Not sure if it's also related to this issue but doing `pngquant ./images/*.png` no longer works for me. It says it couldn't open the path for reading using the latest versions. I had to go back to version 2.9

**Comment by pornel** [comment] 2017-11-17 12:40
Yup, wildcards is another thing that Microsoft's compiler doesn't automatically do. I'll patch over it in the next release — #273

**Comment by PhonyWelder** [comment] 2018-04-25 19:26
If globs on Windows causes problems than maybe drop its support in favor of unicode names (Windows supports UTF-16LE but current pngquant sends UTF-8)? 
Even DOS have "for" command, so basic things like "*.png" will work: https://www.computerhope.com/forhlp.htm

**Comment by kornelski** [comment] 2018-04-25 19:58
I've fixed globs, there are no longer a problem.

The current problem is that `fopen` in MSVC can't handle non-ASCII characters.

**Comment by kornelski** [comment] 2018-04-25 22:12
I'm very reluctant to add ugly non-portable code to work around yet another bug in Microsoft's C compiler.

**Comment by sergeevabc** [comment] 2019-04-30 22:57
Dear Kornel, is there anything a mere user without dev skills could do to expedite a resolution of this issue?

**Comment by kornelski** [comment] 2019-05-03 13:04
No, sorry. I've been busy with lots of other things.

As a user, you can pipe to pngquant instead `pngquant - < 漢字.png > 漢字.png` should always work.

**Comment by kornelski** [comment] 2021-05-08 16:27
This may be fixed in 2.15.0

**Closed by kornelski** 2021-05-08 16:27 UTC
